dist: xenial
language: python
python:
  - "3.6"
install:
  - pip install pipenv
  - pipenv install --dev
  - pipenv install codecov
# command to run tests
script:
  - python3 -m pytest --cov=darkseid tests/

after_success:
  - codecov